replicaCount: 2

image:
  repository: ap-tokyo-1.ocir.io/nrsswwev6ppj/ocir-private:nginx-latest
  tag: stable
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
