replicaCount: 3

image:
  repository: syd.ocir.io/sd7pd0bypgvo/ocir-private
  tag: nginx-latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 80
  annotations:
    # OCI Flexible Load Balancer Annotations
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.ap-sydney-1.aaaaaaaaebkze5om7ypt26z57grzggtyq2anx6xyx7ujbd774zx7tb5wf22a"

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
