replicaCount: 2

image:
  repository: ap-tokyo-1.ocir.io/nrsswwev6ppj/ocir-private
  tag: python-web-latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ocir-secret

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
