name: Build and Push Python Web App to OCIR

on:
  push:
    branches:
      - main
    paths:
      - Python-Based/**

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    name: Build and Push Python Web App to OCIR
    env:
      OCI_USER_OCID: ${{ secrets.OCI_CLI_USER }}
      OCI_TENANCY_OCID: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_PRIVATE_KEY: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE=ap-tokyo-1.ocir.io/nrsswwev6ppj/ocir-private:python-web-latest
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          docker build -t $IMAGE -f Python-Based/Dockerfile Python-Based/

      - name: Push Docker Image
        run: docker push $IMAGE

      - name: Update Deployment Image
        run: |
          sed -i "s|image: .*|image: ${IMAGE}|g" Python-Based/deployment.yaml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Python-Based/deployment.yaml
          git commit -m "Update image to ${IMAGE}" || echo "No changes to commit"
          git push
